/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.*;
import database.koneksi;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ilham-07010
 */
public class surat extends javax.swing.JFrame {

    koneksi koneksi = new koneksi();
    controller controller = new controller();
    String NIK;
    public surat() throws SQLException {
        initComponents();
        jCAdmin();
        getTableSurat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSurat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tgl_surat = new javax.swing.JTextField();
        alamat_surat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        keterangan_surat = new javax.swing.JTextField();
        keperluan_surat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nama_surat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxAdmin = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nik_surat = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        simpan_surat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSurat = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        update_surat = new javax.swing.JButton();
        delete_surat = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nik_update_surat = new javax.swing.JTextField();
        cari_update_surat = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        keterangan_update_surat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        keperluan_update_surat = new javax.swing.JTextField();
        jPanelMenu = new javax.swing.JPanel();
        create_admin = new javax.swing.JButton();
        master = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Admin");

        jLabel4.setText("Alamat");

        jLabel5.setText("Keterangan");

        jLabel6.setText("Keperluan");

        nama_surat.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                nama_suratComponentHidden(evt);
            }
        });

        jLabel7.setText("Nama");

        jComboBoxAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAdminActionPerformed(evt);
            }
        });

        jLabel2.setText("NIK");

        nik_surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nik_suratActionPerformed(evt);
            }
        });

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        simpan_surat.setText("SIMPAN");
        simpan_surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_suratActionPerformed(evt);
            }
        });

        jLabel3.setText("Tanggal Lahir");

        tableSurat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NIK", "Keterangan", "Keperluan"
            }
        ));
        tableSurat.setToolTipText("");
        tableSurat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSuratMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSurat);

        jLabel9.setText("Surat_Surat");

        update_surat.setText("Update");
        update_surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_suratActionPerformed(evt);
            }
        });

        delete_surat.setText("Delete");
        delete_surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_suratActionPerformed(evt);
            }
        });

        jLabel10.setText("NIK");

        jLabel11.setText("Cari Data Surat yang akan di Update / Delete");

        nik_update_surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nik_update_suratActionPerformed(evt);
            }
        });

        cari_update_surat.setText("Cari");
        cari_update_surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_update_suratActionPerformed(evt);
            }
        });

        jLabel12.setText("Keterangan");

        keterangan_update_surat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keterangan_update_suratActionPerformed(evt);
            }
        });

        jLabel13.setText("Keperluan");

        javax.swing.GroupLayout jPanelSuratLayout = new javax.swing.GroupLayout(jPanelSurat);
        jPanelSurat.setLayout(jPanelSuratLayout);
        jPanelSuratLayout.setHorizontalGroup(
            jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuratLayout.createSequentialGroup()
                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuratLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSuratLayout.createSequentialGroup()
                                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSuratLayout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBoxAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nik_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelSuratLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tgl_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nama_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(alamat_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(keterangan_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(keperluan_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(jPanelSuratLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(simpan_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuratLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSuratLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(update_surat)
                                .addGap(18, 18, 18)
                                .addComponent(delete_surat))
                            .addComponent(jLabel11)
                            .addGroup(jPanelSuratLayout.createSequentialGroup()
                                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(42, 42, 42)
                                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(keterangan_update_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(keperluan_update_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelSuratLayout.createSequentialGroup()
                                        .addComponent(nik_update_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(cari_update_surat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelSuratLayout.setVerticalGroup(
            jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuratLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuratLayout.createSequentialGroup()
                        .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nik_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cari)
                            .addComponent(jLabel2))
                        .addGap(5, 5, 5)
                        .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tgl_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(alamat_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(keterangan_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSuratLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(keperluan_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan_surat)
                    .addComponent(jLabel10)
                    .addComponent(nik_update_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari_update_surat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(keterangan_update_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(keperluan_update_surat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_surat)
                    .addComponent(delete_surat))
                .addGap(168, 168, 168))
        );

        create_admin.setText("Create Admin");
        create_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_adminActionPerformed(evt);
            }
        });

        master.setText("Master");
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(master, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(create_admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(master)
                .addGap(18, 18, 18)
                .addComponent(create_admin)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Berkas Mlaku deWe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jLabel8)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSurat, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nik_suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nik_suratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nik_suratActionPerformed

    private void jComboBoxAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAdminActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        String NIKe = nik_surat.getText();
        ResultSet rs = koneksi.GetData("select NAMA_LENGKAP, TANGGAL_LAHIR, ALAMAT from master where NIK ='"+NIKe+"'");
        try {
            while (rs.next()){
                nama_surat.setText(rs.getString("NAMA_LENGKAP"));
                tgl_surat.setText(rs.getString("TANGGAL_LAHIR"));
                alamat_surat.setText(rs.getString("ALAMAT"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cariActionPerformed

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed
        try {
        new master().show();
        setVisible(false);
    } catch (SQLException ex) {
        Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_masterActionPerformed

    private void nama_suratComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_nama_suratComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_suratComponentHidden

    private void simpan_suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_suratActionPerformed
        String nik = nik_surat.getText();
        String keterangan = keterangan_surat.getText();
        String keperluan = keperluan_surat.getText();
        int id_user = 0;
        try {
            id_user = idUser(jComboBoxAdmin.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(master.class.getName()).log(Level.SEVERE, null, ex);
        }
        controller.InsertSurat(id_user, nik, keterangan, keperluan);
        try {
            getTableSurat();
        } catch (SQLException ex) {
            Logger.getLogger(master.class.getName()).log(Level.SEVERE, null, ex);
        }
        nik_surat.setText("");
        nama_surat.setText("");
        tgl_surat.setText("");
        alamat_surat.setText("");
        keterangan_surat.setText("");
        keperluan_surat.setText("");
    }//GEN-LAST:event_simpan_suratActionPerformed

    private void update_suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_suratActionPerformed
        String nik = nik_update_surat.getText();
        String keterangan = keterangan_update_surat.getText();
        String keperluan = keperluan_update_surat.getText();
        controller.UpdateSurat(nik, keterangan, keperluan);
        try {
            getTableSurat();
        } catch (SQLException ex) {
            Logger.getLogger(master.class.getName()).log(Level.SEVERE, null, ex);
        }
        nik_update_surat.setText("");
        keterangan_update_surat.setText("");
        keperluan_update_surat.setText("");
    }//GEN-LAST:event_update_suratActionPerformed

    private void tableSuratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSuratMouseClicked
        //
    }//GEN-LAST:event_tableSuratMouseClicked

    private void keterangan_update_suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keterangan_update_suratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keterangan_update_suratActionPerformed

    private void nik_update_suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nik_update_suratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nik_update_suratActionPerformed

    private void cari_update_suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_update_suratActionPerformed
    String NIKe = nik_update_surat.getText();
        ResultSet rs = koneksi.GetData("select NIK, KETERANGAN, KEPERLUAN from surat_surat where NIK ='"+NIKe+"'");
        try {
            while (rs.next()){
                nik_update_surat.setText(rs.getString("NIK"));
                keterangan_update_surat.setText(rs.getString("KETERANGAN"));
                keperluan_update_surat.setText(rs.getString("KEPERLUAN"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_cari_update_suratActionPerformed

    private void delete_suratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_suratActionPerformed
        String nik = nik_update_surat.getText();
        controller.DeleteSurat(nik);
         try {
            getTableSurat();
        } catch (SQLException ex) {
            Logger.getLogger(master.class.getName()).log(Level.SEVERE, null, ex);
        }
        nik_update_surat.setText("");
        keterangan_update_surat.setText("");
        keperluan_update_surat.setText("");
    }//GEN-LAST:event_delete_suratActionPerformed

    private void create_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_adminActionPerformed
        try {
        new CreateAdmin().show();
        setVisible(false);
    } catch (SQLException ex) {
        Logger.getLogger(CreateAdmin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_create_adminActionPerformed
    
        private void jCAdmin() throws SQLException{
        ResultSet rs = koneksi.GetData("select username from admin");
        int i = 1;
        jComboBoxAdmin.removeAllItems();
        while (rs.next()){
            jComboBoxAdmin.addItem(rs.getString("USERNAME"));
        }
        jComboBoxAdmin.repaint();
        jComboBoxAdmin.revalidate();
    }
        private int idUser(String username) throws SQLException{
        int id_User = 0;
        ResultSet rs = koneksi.GetData("select id_user from admin where username = '"+username+"'");
        while(rs.next()){
            id_User = rs.getInt("id_user");
        
        }
        return id_User;
    }
        private void getTableSurat() throws SQLException{
        String sql = "select a.nama_lengkap as NAMA_LENGKAP, b.nik as NIK, b.keterangan as KETERANGAN, b.keperluan as KEPERLUAN from master a join surat_surat b on a.nik = b.nik";
        ResultSet set = koneksi.GetData(sql);
        DefaultTableModel model = (DefaultTableModel)tableSurat.getModel();
        model.setRowCount(0);
        try {
            while(set.next()){
                model.addRow(new Object[]{
                    set.getString("NAMA_LENGKAP"),
                    set.getLong("NIK"),
                    set.getString("KETERANGAN"),
                    set.getString("KEPERLUAN")                    
                    });
                }
            }catch(SQLException ex){
            System.out.println(ex);
            }
        }
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(surat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(surat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(surat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(surat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new surat().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(surat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat_surat;
    private javax.swing.JButton cari;
    private javax.swing.JButton cari_update_surat;
    private javax.swing.JButton create_admin;
    private javax.swing.JButton delete_surat;
    private javax.swing.JComboBox jComboBoxAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelSurat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keperluan_surat;
    private javax.swing.JTextField keperluan_update_surat;
    private javax.swing.JTextField keterangan_surat;
    private javax.swing.JTextField keterangan_update_surat;
    private javax.swing.JButton master;
    private javax.swing.JTextField nama_surat;
    private javax.swing.JTextField nik_surat;
    private javax.swing.JTextField nik_update_surat;
    private javax.swing.JButton simpan_surat;
    private javax.swing.JTable tableSurat;
    private javax.swing.JTextField tgl_surat;
    private javax.swing.JButton update_surat;
    // End of variables declaration//GEN-END:variables

    private boolean getValueAt(int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
